apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/mysql/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1 
kind: StatefulSet 
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql-statefulset001
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
# ---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: mysql
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:5.6
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               value: "123456"
#           #   - name: POSTGRES_USER
#           #     value: kong
#           #   - name: POSTGRES_PASSWORD
#           #     value: kong
#           #   - name: POSTGRES_DB
#           #     value: kong
#           #   - name: PGDATA
#           #     value: /var/lib/postgresql/data/pgdata
#           ports:
#             - containerPort: 3306
#           volumeMounts:
#             - mountPath: /data
#               name: mysql-data
#       volumes:
#         - name: mysql-data
#           emptyDir: {}
